name: Release Drafter

on:
  push:
    branches:
      - release/*

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.update_release_draft.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      # Get the last tag created on this branch
      - name: Get Last Tag
        id: last_tag
        run: |
          LASTTAG=$(git describe --tags | sed -re "s/-.+//")
          echo "::set-output name=last_tag_on_branch::$LASTTAG"

      - name: Draft Release
        id: update_release_draft
        uses: tiller1010/release-drafter@master
        with:
          last_tag: ${{ steps.last_tag.outputs.last_tag_on_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
