name: Publish draft release when release branch is merged

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - 'releases/**'
on:
  push:
    branches:
      - main


jobs:
  if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # outputs:
    #   output: ${{ steps.get_release_id.outputs.release_id }}
    steps:
      # - name: Get release id
      #   id: get_release_id
      #   run: |
      #     RELEASEID=$(git describe --tags | sed -re "s/-.+//")
      #     echo "::set-output name=release_id::$RELEASEID"

      - name: Get release id
        id: get_release_id
        uses: agners/get-draft-release@v0.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.get_release_id.outputs.id }}
