name: Sync develop branch with main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Pass credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main
        run: |
          git fetch
          git checkout main
          git checkout develop
          git merge main -s resolve --allow-unrelated-histories
          git push
