name: Sync develop branch with main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Merge main
        run: |
          git fetch
          git checkout main
          git checkout develop
          git merge main -s recursive -X theirs --allow-unrelated-histories
